baseballcardcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('cards/', views.cards_index, name='index'),
    path('cards/<int:card_id>', views.cards_detail, name="detail"),
    path('cards/create/', views.CardCreate.as_view(), name='cards_create'),
    path('cards/<int:pk>/update/', views.CardUpdate.as_view(), name='cards_update'),
    path('cards/<int:pk>/delete/', views.CardDelete.as_view(), name='cards_delete'),
    path('cards/<int:card_id>/add_winner/',
         views.add_winner, name='add_winner'),
    path('cards/<int:card_id>/assoc_case/<int:case_id>/',
         views.assoc_case, name='assoc_case'),
    path('cards/<int:card_id>/add_photo/', views.add_photo, name='add_photo'),
    path('cases/', views.CaseList.as_view(), name='cases_index'),
    path('cases/<int:pk>/', views.CaseDetail.as_view(), name='cases_detail'),
    path('cases/create/', views.CaseCreate.as_view(), name='cases_create'),
    path('cases/<int:pk>/update/', views.CaseUpdate.as_view(), name='cases_update'),
    path('cases/<int:pk>/delete/', views.CaseDelete.as_view(), name='cases_delete'),
    path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

MATERIALS = (
    ('P', 'Plastic'),
    ('G', 'Glass')
)

LEAGUES = (
    ('NL', 'National League'),
    ('AL', 'American League')
)

AWARDS = (
    ('MVP', 'MVP'),
    ('CY', 'Cy Young'),
    ('ROTY', 'Rookie of the Year')
)

# Create your models here.


class Case(models.Model):
    type = models.CharField(max_length=100)
    material = models.CharField(
        max_length=1,
        choices=MATERIALS,
        default=MATERIALS[0][0]
    )

    def __str__(self):
        return self.type

    def get_absolute_url(self):
        return reverse('cases_detail', kwargs={'pk': self.id})


class Card(models.Model):
    name = models.CharField(max_length=100)
    position = models.CharField(max_length=100)
    seasons = models.IntegerField()
    brand = models.CharField(max_length=100)
    year = models.IntegerField()
    cases = models.ManyToManyField(Case)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'card_id': self.id})

    def should_get_case(self):
        return self.seasons == 0


class Winner(models.Model):
    year = models.IntegerField()
    league = models.CharField(
        max_length=2,
        choices=LEAGUES,
        default=LEAGUES[0][0]
    )
    award = models.CharField(
        max_length=4,
        choices=AWARDS,
        default=AWARDS[0][0]
    )
    card = models.ForeignKey(Card, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.year} {self.get_league_display()} {self.get_award_display()}"

    class Meta:
        ordering = ['-year']


class Photo(models.Model):
    url = models.CharField(max_length=200)
    card = models.ForeignKey(Card, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for card_id: {self.card_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Winner


class WinnerForm(ModelForm):
    class Meta:
        model = Winner
        fields = ['year', 'league', 'award']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Card, Case, Photo
from .forms import WinnerForm
import os
import uuid
import boto3


class CardCreate(LoginRequiredMixin, CreateView):
    model = Card
    fields = ['name', 'position', 'seasons', 'brand', 'year']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class CardUpdate(LoginRequiredMixin, UpdateView):
    model = Card
    fields = ['position', 'seasons', 'brand', 'year']


class CardDelete(LoginRequiredMixin, DeleteView):
    model = Card
    success_url = '/cards/'

# Create your views here.


def home(request):
    return render(request, 'home.html')


def about(request):
    return render(request, 'about.html')


def cards_index(request):
    cards = Card.objects.all()
    return render(request, 'cards/index.html', {'cards': cards})


@login_required
def cards_detail(request, card_id):
    card = Card.objects.get(id=card_id)
    winner_form = WinnerForm()
    return render(request, 'cards/detail.html', {
        'card': card,
        'winner_form': winner_form
    })


@login_required
def add_winner(request, card_id):
    form = WinnerForm(request.POST)
    if form.is_valid():
        new_winner = form.save(commit=False)
        new_winner.card_id = card_id
        new_winner.save()
    return redirect('detail', card_id=card_id)


def cards_detail(request, card_id):
    card = Card.objects.get(id=card_id)
    cases_card_doesnt_have = Case.objects.exclude(
        id__in=card.cases.all().values_list('id'))
    winner_form = WinnerForm()
    return render(request, 'cards/detail.html', {
        'card': card, 'winner_form': winner_form,
        'cases': cases_card_doesnt_have
    })


@login_required
def assoc_case(request, card_id, case_id):
    Card.objects.get(id=card_id).cases.add(case_id)
    return redirect('detail', card_id=card_id)


@login_required
def add_photo(request, card_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + \
            photo_file.name[photo_file.name.rfind('.'):]
        try:
            bucket = os.environ['S3_BUCKET']
            s3.upload_fileobj(photo_file, bucket, key)
            url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
            Photo.objects.create(url=url, card_id=card_id)
        except:
            print('An error occurred uploading file to S3')
        return redirect('detail', card_id=card_id)


def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('index')
        else:
            error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)


@login_required
def cards_index(request):
    cards = request.user.card_set.all()
    return render(request, 'cards/index.html', {'cards': cards})


class CaseList(LoginRequiredMixin, ListView):
    model = Case


class CaseDetail(LoginRequiredMixin, DetailView):
    model = Case


class CaseCreate(LoginRequiredMixin, CreateView):
    model = Case
    fields = '__all__'


class CaseUpdate(LoginRequiredMixin, UpdateView):
    model = Case
    fields = ['type', 'material']


class CaseDelete(LoginRequiredMixin, DeleteView):
    model = Case
    success_url = '/cases/'

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Baseball Card Collector</h1>
<hr />
<p>Hire the Baseball Card Collector!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Baseball Card Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>

<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="{% url 'home' %}" class="left brand-logo">&nbsp;&nbsp;BaseballCardCollector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          {% if user.is_authenticated %}
            <li><a href="{% url 'cases_create' %}">Add a Case</a></li>
            <li><a href="{% url 'cases_index' %}">View All Cases</a></li>
            <li><a href="{% url 'cards_create' %}">Add a Card</a></li>
            <li><a href="{% url 'index' %}">View All My Baseball Cards</a></li>
            <li><a href="{% url 'logout' %}">Log Out</a></li>
          {% else %}
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
            <li><a href="{% url 'login' %}">Log In</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2022 Baseball Card Collector &nbsp;</div>
  </footer>
</body>

</html>

main_app/templates/cards/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Baseball Card Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ card.name }}</span>
        <p>Position: {{ card.position }}</p>
        {% if card.seasons > 0 %}
        <p>Years in MLB: {{ card.seasons }}</p>
        {% else %}
        <p>Rookie Card</p>
        {% endif %}
        <p>Card Brand: {{ card.brand }}</p>
        <p>Year: {{ card.year }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'cards_update' card.id %}">Edit</a>
        <a href="{% url 'cards_delete' card.id %}">Delete</a>
      </div>
    </div>
    {% for photo in card.photo_set.all %}
      <img class="responsive-img card-panel" src="{{photo.url}}">
    {% empty %}
      <div class="card-panel teal-text center-align">No Photos Uploaded</div>
    {% endfor %}
    <form action="{% url 'add_photo' card.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
      {% csrf_token %}
      <input type="file" name="photo-file">
      <br><br>
      <input type="submit" class="btn" value="Upload Photo">
    </form>
  </div>
  <div class="col s6">
    <form action="{% url 'add_winner' card.id %}" method="POST">
      {% csrf_token %}
      {{ winner_form.as_p }}
      <input type="submit" class="btn" value="Add Award">
    </form>
    <br>
    {% if card.should_get_case %}
    <div class="card-panel red-text center-align">This {{card.name}} Rookie card may have a high value. You should protect it with several different cases.</div>
    {% else %}
    <div class="card-panel teal-text center-align">This {{card.name}} card is probably not very valuable. A simple case will do.</div>
    {% endif %}
    <table class="striped">
      <thead>
        <tr>
          <th>Year</th>
          <th>League</th>
          <th>Award</th>
        </tr>
      </thead>
      <tbody>
        {% for winner in card.winner_set.all %}
        <tr>
          <td>{{winner.year}}</td>
          <td>{{winner.get_league_display}}</td>
          <td>{{winner.get_award_display}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ card.name }}'s Cases</h3>
    {% if card.cases.count %}
      {% for case in card.cases.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span style="material: {{ case.material }}">{{ case.get_material_display }}</span> {{ case.type }}
            </span>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Cases :(</h5>
    {% endif %}
  </div>
  <div class="col s6">
    <h3>Available Cases</h3>
    {% if cases.count %}
      {% for case in cases.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span style="material: {{ case.material }}">{{ case.get_material_display }}</span> {{ case.type }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_case' card.id case.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>This {{card.name}} Card Already Has All Cases Available</h5>
    {% endif %}
  </div>
</div>
<script>
  const leagueEl = document.getElementById('id_league');
  M.FormSelect.init(leagueEl)
  const awardEl = document.getElementById('id_award');
  M.FormSelect.init(awardEl)
</script>
{% endblock %}

main_app/templates/cards/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Baseball Card List</h1>

{% for card in cards %}
<div class="card">
  <a href="{% url 'detail' card.id %}">
    <div class="card-content">
      <span class="card-title">{{ card.name }}</span>
      <p>Position: {{ card.position }}</p>
      {% if card.seasons > 0 %}
      <p>Years in MLB: {{ card.seasons }}</p>
      {% else %}
      <p>Rookie Card</p>
      {% endif %}
      <p>Card Brand: {{ card.brand }}</p>
      <p>Year: {{ card.year }}</p>
    </div>
  </a>
</div>
{% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Home</h1>

{% endblock %}

main_app/templates/main_app/card_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Card</h1>

  <h4>Are you sure you want to delete the <span class="teal-text">{{ object.name }}</span> baseball card?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' card.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/card_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Card</h1>
  {% endif %}
  <form action="" method=POST>
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/case_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>Delete Case</h1>

<h4>Are you sure you want to delete <span class="teal-text">{{ object.material }}{{ object.type }}</span>?</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn">
  <a href="{% url 'cases_detail' object.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/case_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Case Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ case.type }}</span>
        <p>Material: {{ case.get_material_display }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'cases_update' case.id %}">Edit</a>
        <a href="{% url 'cases_delete' case.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/case_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
<h1>Edit <span class="teal-text">{{object.get_material_display}} {{object.type}}</span></h1>
{% else %}
<h1>Add Case</h1>
{% endif %}
<form action="" method="POST">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn">
</form>

<script>
  const materialEl = document.getElementById('id_material');
  M.FormSelect.init(materialEl)
</script>
{% endblock %}

main_app/templates/main_app/case_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Case List</h1>

{% for case in case_list %}
<a href="{% url 'cases_detail' case.id %}">
  <div class="card">
    <div class="card-content">
      <span class="card-title">{{ case.type }}</span>
      <p>Material: {{ case.get_material_display }}</p>
    </div>
  </div>
</a>
{% endfor %}

{% endblock %}